# Generated by Django 4.2.24 on 2025-09-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batvat', '0002_feeding'),
    ]

    operations = [
    ]
