# Generated by Django 4.2.24 on 2025-09-11 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batvat', '0004_toy_alter_feeding_options_bat_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
