# Generated by Django 4.2.24 on 2025-09-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batvat', '0005_toy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bats/'),
        ),
    ]
